#!/usr/bin/env bash
# shell script to install nginx and add add_header
sudo apt update
sudo apt -y install nginx
sudo sed -i '/server_name _;/a\ add_header X-Served-By $hostname;' /etc/nginx/sites-available/default
sudo service nginx restart
echo "Nginx configured with custom X-Served-By header"
