#!/usr/bin/env bash
# Installs Nginx and configures it to return a custom X-Served-By header set to the server's hostname

set -e

apt-get update -y
apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.nginx-debian.html

if ! grep -q "X-Served-By" /etc/nginx/sites-available/default; then
    sed -i "/server_name _;/a \\\tadd_header X-Served-By \$hostname always;" /etc/nginx/sites-available/default
fi

nginx -t
service nginx restart
