#!/usr/bin/env bash
# Installs HAProxy and configures it to load-balance traffic across web-01 and web-02 using round robin

set -e

# shellcheck disable=SC2154

apt-get update -y
apt-get install -y haproxy

sed -i "s/ENABLED=0/ENABLED=1/" /etc/default/haproxy

if [ ! -f /etc/haproxy/haproxy.cfg.orig ]; then
    cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.orig
fi

cat >> /etc/haproxy/haproxy.cfg <<EOF

frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server 7170-web-01 3.88.19.0:80 check
    server 7170-web-02 52.87.160.149:80 check
EOF

service haproxy restart
