#!/usr/bin/env bash
# Installs and configures HAProxy to load balance between web-01 and web-02
apt-get update -y
apt-get install -y haproxy

cat >> /etc/haproxy/haproxy.cfg << 'EOF'

frontend http_front
	bind *:80
	default_backend http_back

backend http_back
	balance roundrobin
	server 7087-web-01 3.88.19.0:80 check
	server 7087-web-02 52.87.160.149:80 check
EOF

sed -i 's/^ENABLED=.*/ENABLED=1/' /etc/default/haproxy

service haproxy restart
